/* 
DO NOT EDIT FILE 
This file is autogenerated with src/devScripts/generateTinyBaseSchemas.ts
*/

/**
 * Auto-generated tinyBase schema
 */
export const tinyBaseRecordDraftSchema = {
  "institutions": {
    "name": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "isDirty": {
      "type": "boolean"
    },
    "isDeleted": {
      "type": "boolean"
    },
    "isNew": {
      "type": "boolean"
    }
  },
  "assets": {
    "institution": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "amount": {
      "type": "number"
    },
    "currency": {
      "type": "string"
    },
    "isEarning": {
      "type": "boolean"
    },
    "description": {
      "type": "string"
    },
    "isDirty": {
      "type": "boolean"
    },
    "isDeleted": {
      "type": "boolean"
    },
    "isNew": {
      "type": "boolean"
    }
  },
  "quotes": {
    "date": {
      "type": "number"
    },
    "baseCurrency": {
      "type": "string"
    },
    "counterCurrency": {
      "type": "string"
    },
    "rate": {
      "type": "number"
    }
  },
  "meta": {
    "journalId": {
      "type": "string"
    }
  }
} as const;
